name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  bazel:
    name: Bazel
    runs-on: macos-13
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build
      run: bazelisk build :all
    - name: Test
      run: bazelisk test :all
    - name: Validate executables
      run: |
        bazelisk run --macos_minimum_os=$(sw_vers -productVersion) :nodes-code-gen -- --help
        bazelisk run --macos_minimum_os=$(sw_vers -productVersion) :nodes-xcode-templates-gen -- --help
